-- Thứ tự tạo bảng phải theo đúng dependency (FK):
--   1. ROLES           — không phụ thuộc ai
--   2. PERMISSIONS     — không phụ thuộc ai
--   3. ROLE_PERMISSIONS — phụ thuộc ROLES + PERMISSIONS
--   4. USERS           — phụ thuộc ROLES
--   5. STUDENT_PROFILES — phụ thuộc USERS
--   6. TEACHER_PROFILES — phụ thuộc USERS
--
-- Thứ tự DROP ngược lại để tránh FK violation.
-- Chạy script này 1 lần khi khởi tạo DB lần đầu.


-- Xóa bảng cũ nếu tồn tại (để có thể chạy lại script)
-- Thứ tự DROP ngược với thứ tự CREATE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADMIN_PROFILES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEACHER_PROFILES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE STUDENT_PROFILES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ROLE_PERMISSIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERMISSIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ROLES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/


-- ----------------------------------------------------------------
-- 1. ROLES
-- Seeded data: Student, Teacher, Admin
-- ROLE_ID dùng GENERATED ALWAYS AS IDENTITY 
CREATE TABLE ROLES (
    ROLE_ID    NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE_NAME  VARCHAR2(50)    NOT NULL,
    CONSTRAINT UQ_ROLES_NAME UNIQUE (ROLE_NAME)
);

-- 2. PERMISSIONS
-- Seeded data: tất cả các PermissionType trong enum
CREATE TABLE PERMISSIONS (
    PERMISSION_ID    NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PERMISSION_TYPE  VARCHAR2(100)   NOT NULL,
    CONSTRAINT UQ_PERMISSIONS_TYPE UNIQUE (PERMISSION_TYPE)
);

-- 3. ROLE_PERMISSIONS
-- Mapping nhiều-nhiều giữa ROLES và PERMISSIONS.
-- Composite PK đảm bảo không có row trùng lặp.
-- Seeded data: mapping theo DEFAULT_ROLE_PERMISSIONS
CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID        NUMBER  NOT NULL,
    PERMISSION_ID  NUMBER  NOT NULL,
    CONSTRAINT PK_ROLE_PERMISSIONS PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES (ROLE_ID),
    CONSTRAINT FK_RP_PERMISSION FOREIGN KEY (PERMISSION_ID)
        REFERENCES PERMISSIONS (PERMISSION_ID)
);

-- 4. USERS
CREATE TABLE USERS (
    USER_ID        VARCHAR2(36)    PRIMARY KEY,
    EMAIL          VARCHAR2(255)   NOT NULL,
    PASSWORD_HASH  VARCHAR2(255)   NOT NULL,
    FULL_NAME      VARCHAR2(100)   NOT NULL,
    ROLE_ID        NUMBER          NOT NULL,
    CONSTRAINT UQ_USERS_EMAIL   UNIQUE (EMAIL),
    CONSTRAINT FK_USERS_ROLE    FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES (ROLE_ID)
);


-- 5. STUDENT_PROFILES
-- Quan hệ 1-1 với USERS — USER_ID vừa là PK vừa là FK.
-- ON DELETE CASCADE: xóa USERS thì xóa profile theo.
-- AVERAGE_SCORE dùng NUMBER(5,2): tối đa 999.99
CREATE TABLE STUDENT_PROFILES (
    USER_ID                 VARCHAR2(36)    PRIMARY KEY,
    MAJOR                   VARCHAR2(100)   NOT NULL,
    AVERAGE_SCORE           NUMBER(5,2)     DEFAULT 0 NOT NULL,
    COMPLETED_QUIZ_ATTEMPTS NUMBER          DEFAULT 0 NOT NULL,
    CONSTRAINT FK_SP_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID) ON DELETE CASCADE
);


-- 6. TEACHER_PROFILES
-- Quan hệ 1-1 với USERS.
CREATE TABLE TEACHER_PROFILES (
    USER_ID          VARCHAR2(36)    PRIMARY KEY,
    DEPARTMENT       VARCHAR2(100)   NOT NULL,
    QUIZZES_CREATED  NUMBER          DEFAULT 0 NOT NULL,
    CONSTRAINT FK_TP_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID) ON DELETE CASCADE
);