-- Chạy sau init.sql bằng SQL client (SQL Developer / SQLPlus / DBeaver)
-- Sau khi chạy file này: academic/init.sql → academic/seed.sql
-- (TEACHING_ASSIGNMENTS và ENROLLMENTS có FK → USERS nên phải chạy file này trước)

--   Phần 1 — Static data: Roles, Permissions, RolePermissions
--   Phần 2 — Sample accounts: 1 Admin, 3 Teacher, 4 Student
--
-- Passwords mặc định:
--   Admin   : Admin@123
--   Teacher : Teacher@123
--   Student : Student@123
--
-- Hash được pre-compute bằng bcrypt (cost=10) — khớp với
-- BcryptPasswordHasher.ts trong infrastructure layer.
--
-- UUID cố định để script idempotent — chạy lại không duplicate.

-- ROLES
INSERT INTO ROLES (ROLE_NAME)
SELECT 'Student' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLE_NAME = 'Student');

INSERT INTO ROLES (ROLE_NAME)
SELECT 'Teacher' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLE_NAME = 'Teacher');

INSERT INTO ROLES (ROLE_NAME)
SELECT 'Admin' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLE_NAME = 'Admin');


-- PERMISSIONS
INSERT INTO PERMISSIONS (PERMISSION_TYPE)
SELECT 'ATTEMPT_QUIZ' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_TYPE = 'ATTEMPT_QUIZ');

INSERT INTO PERMISSIONS (PERMISSION_TYPE)
SELECT 'VIEW_OWN_RESULT' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_TYPE = 'VIEW_OWN_RESULT');

INSERT INTO PERMISSIONS (PERMISSION_TYPE)
SELECT 'VIEW_CLASS_RANKING' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_TYPE = 'VIEW_CLASS_RANKING');

INSERT INTO PERMISSIONS (PERMISSION_TYPE)
SELECT 'VIEW_SECTION' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_TYPE = 'VIEW_SECTION');

INSERT INTO PERMISSIONS (PERMISSION_TYPE)
SELECT 'CREATE_QUIZ' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_TYPE = 'CREATE_QUIZ');

INSERT INTO PERMISSIONS (PERMISSION_TYPE)
SELECT 'EDIT_QUIZ' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_TYPE = 'EDIT_QUIZ');

INSERT INTO PERMISSIONS (PERMISSION_TYPE)
SELECT 'PUBLISH_QUIZ' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_TYPE = 'PUBLISH_QUIZ');

INSERT INTO PERMISSIONS (PERMISSION_TYPE)
SELECT 'HIDE_QUIZ' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_TYPE = 'HIDE_QUIZ');

INSERT INTO PERMISSIONS (PERMISSION_TYPE)
SELECT 'VIEW_ANALYTICS' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_TYPE = 'VIEW_ANALYTICS');

INSERT INTO PERMISSIONS (PERMISSION_TYPE)
SELECT 'VIEW_AT_RISK_STUDENTS' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_TYPE = 'VIEW_AT_RISK_STUDENTS');

INSERT INTO PERMISSIONS (PERMISSION_TYPE)
SELECT 'VIEW_HIERARCHICAL_REPORT' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_TYPE = 'VIEW_HIERARCHICAL_REPORT');


-- ROLE_PERMISSIONS
-- Dùng subquery JOIN theo name vì GENERATED ALWAYS AS IDENTITY
-- không biết trước ID là bao nhiêu

-- Student
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Student' AND P.PERMISSION_TYPE = 'ATTEMPT_QUIZ'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Student' AND P.PERMISSION_TYPE = 'VIEW_OWN_RESULT'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Student' AND P.PERMISSION_TYPE = 'VIEW_CLASS_RANKING'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Student' AND P.PERMISSION_TYPE = 'VIEW_SECTION'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

-- Teacher
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Teacher' AND P.PERMISSION_TYPE = 'CREATE_QUIZ'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Teacher' AND P.PERMISSION_TYPE = 'EDIT_QUIZ'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Teacher' AND P.PERMISSION_TYPE = 'PUBLISH_QUIZ'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Teacher' AND P.PERMISSION_TYPE = 'HIDE_QUIZ'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Teacher' AND P.PERMISSION_TYPE = 'ATTEMPT_QUIZ'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Teacher' AND P.PERMISSION_TYPE = 'VIEW_OWN_RESULT'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Teacher' AND P.PERMISSION_TYPE = 'VIEW_ANALYTICS'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Teacher' AND P.PERMISSION_TYPE = 'VIEW_AT_RISK_STUDENTS'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Teacher' AND P.PERMISSION_TYPE = 'VIEW_CLASS_RANKING'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Teacher' AND P.PERMISSION_TYPE = 'VIEW_SECTION'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

-- Admin
INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Admin' AND P.PERMISSION_TYPE = 'VIEW_ANALYTICS'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Admin' AND P.PERMISSION_TYPE = 'VIEW_HIERARCHICAL_REPORT'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Admin' AND P.PERMISSION_TYPE = 'VIEW_AT_RISK_STUDENTS'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Admin' AND P.PERMISSION_TYPE = 'VIEW_CLASS_RANKING'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);

INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT R.ROLE_ID, P.PERMISSION_ID FROM ROLES R, PERMISSIONS P
WHERE R.ROLE_NAME = 'Admin' AND P.PERMISSION_TYPE = 'VIEW_SECTION'
AND NOT EXISTS (SELECT 1 FROM ROLE_PERMISSIONS RP WHERE RP.ROLE_ID = R.ROLE_ID AND RP.PERMISSION_ID = P.PERMISSION_ID);


-- PHẦN 2: SAMPLE ACCOUNTS
--
-- Password hashes (bcrypt cost=10, pre-computed):
--   Admin@123   : $2b$10$ul9gVsHrrmY1s.BjhVXnvefYXoZ7FaD6r84pgLzNZj5tOkoYVHBDK
--   Teacher@123 : $2b$10$pZpXuliMF7VgQNuAkF5NMeQOxH2BsVSx8jCqTU1.prDFOIFZqIAJW
--   Student@123 : $2b$10$dpWgPcUSPz52lisQnwyqW.1JHSX8hEq4UqTmD0ex/XoGK1ZdpagsG
--
-- UUID cố định để WHERE NOT EXISTS hoạt động đúng khi chạy lại.


-- ADMIN (1 account)
INSERT INTO USERS (USER_ID, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE_ID)
SELECT
    '7e8c7f25-b4b8-49c0-bff0-2f77ae72c16c',
    'admin@school.edu.vn',
    '$2b$10$ul9gVsHrrmY1s.BjhVXnvefYXoZ7FaD6r84pgLzNZj5tOkoYVHBDK',
    'System Admin',
    R.ROLE_ID
FROM ROLES R WHERE R.ROLE_NAME = 'Admin'
AND NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'admin@school.edu.vn');


-- TEACHERS (3 accounts)
INSERT INTO USERS (USER_ID, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE_ID)
SELECT
    '5ace9824-8570-44ce-82fc-acb45eb70aa7',
    'nguyen.van.an@school.edu.vn',
    '$2b$10$pZpXuliMF7VgQNuAkF5NMeQOxH2BsVSx8jCqTU1.prDFOIFZqIAJW',
    'Nguyễn Văn An',
    R.ROLE_ID
FROM ROLES R WHERE R.ROLE_NAME = 'Teacher'
AND NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'nguyen.van.an@school.edu.vn');

INSERT INTO TEACHER_PROFILES (USER_ID, DEPARTMENT, QUIZZES_CREATED)
SELECT '5ace9824-8570-44ce-82fc-acb45eb70aa7', 'Công nghệ thông tin', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TEACHER_PROFILES WHERE USER_ID = '5ace9824-8570-44ce-82fc-acb45eb70aa7');

INSERT INTO USERS (USER_ID, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE_ID)
SELECT
    '43496440-f4ee-491f-be20-1f4235a5072d',
    'tran.thi.bich@school.edu.vn',
    '$2b$10$pZpXuliMF7VgQNuAkF5NMeQOxH2BsVSx8jCqTU1.prDFOIFZqIAJW',
    'Trần Thị Bích',
    R.ROLE_ID
FROM ROLES R WHERE R.ROLE_NAME = 'Teacher'
AND NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'tran.thi.bich@school.edu.vn');

INSERT INTO TEACHER_PROFILES (USER_ID, DEPARTMENT, QUIZZES_CREATED)
SELECT '43496440-f4ee-491f-be20-1f4235a5072d', 'Công nghệ thông tin', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TEACHER_PROFILES WHERE USER_ID = '43496440-f4ee-491f-be20-1f4235a5072d');

INSERT INTO USERS (USER_ID, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE_ID)
SELECT
    '7cc9844b-64d1-447f-9cc1-6fae76d8bd4e',
    'le.minh.duc@school.edu.vn',
    '$2b$10$pZpXuliMF7VgQNuAkF5NMeQOxH2BsVSx8jCqTU1.prDFOIFZqIAJW',
    'Lê Minh Đức',
    R.ROLE_ID
FROM ROLES R WHERE R.ROLE_NAME = 'Teacher'
AND NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'le.minh.duc@school.edu.vn');

INSERT INTO TEACHER_PROFILES (USER_ID, DEPARTMENT, QUIZZES_CREATED)
SELECT '7cc9844b-64d1-447f-9cc1-6fae76d8bd4e', 'Công nghệ thông tin', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TEACHER_PROFILES WHERE USER_ID = '7cc9844b-64d1-447f-9cc1-6fae76d8bd4e');


-- STUDENTS (4 accounts)
INSERT INTO USERS (USER_ID, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE_ID)
SELECT
    'aa477b19-1aad-467d-810f-a48876856240',
    'sv001@student.school.edu.vn',
    '$2b$10$dpWgPcUSPz52lisQnwyqW.1JHSX8hEq4UqTmD0ex/XoGK1ZdpagsG',
    'Phạm Quốc Bảo',
    R.ROLE_ID
FROM ROLES R WHERE R.ROLE_NAME = 'Student'
AND NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'sv001@student.school.edu.vn');

INSERT INTO STUDENT_PROFILES (USER_ID, MAJOR, AVERAGE_SCORE, COMPLETED_QUIZ_ATTEMPTS)
SELECT 'aa477b19-1aad-467d-810f-a48876856240', 'Kỹ thuật phần mềm', 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM STUDENT_PROFILES WHERE USER_ID = 'aa477b19-1aad-467d-810f-a48876856240');

INSERT INTO USERS (USER_ID, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE_ID)
SELECT
    '688eacd1-4651-4feb-a107-7cf140e9dc90',
    'sv002@student.school.edu.vn',
    '$2b$10$dpWgPcUSPz52lisQnwyqW.1JHSX8hEq4UqTmD0ex/XoGK1ZdpagsG',
    'Hoàng Thị Mai',
    R.ROLE_ID
FROM ROLES R WHERE R.ROLE_NAME = 'Student'
AND NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'sv002@student.school.edu.vn');

INSERT INTO STUDENT_PROFILES (USER_ID, MAJOR, AVERAGE_SCORE, COMPLETED_QUIZ_ATTEMPTS)
SELECT '688eacd1-4651-4feb-a107-7cf140e9dc90', 'Kỹ thuật phần mềm', 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM STUDENT_PROFILES WHERE USER_ID = '688eacd1-4651-4feb-a107-7cf140e9dc90');

INSERT INTO USERS (USER_ID, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE_ID)
SELECT
    'bb762538-25c7-48e8-b7e9-7e6562433d4d',
    'sv003@student.school.edu.vn',
    '$2b$10$dpWgPcUSPz52lisQnwyqW.1JHSX8hEq4UqTmD0ex/XoGK1ZdpagsG',
    'Vũ Đình Khoa',
    R.ROLE_ID
FROM ROLES R WHERE R.ROLE_NAME = 'Student'
AND NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'sv003@student.school.edu.vn');

INSERT INTO STUDENT_PROFILES (USER_ID, MAJOR, AVERAGE_SCORE, COMPLETED_QUIZ_ATTEMPTS)
SELECT 'bb762538-25c7-48e8-b7e9-7e6562433d4d', 'Kỹ thuật phần mềm', 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM STUDENT_PROFILES WHERE USER_ID = 'bb762538-25c7-48e8-b7e9-7e6562433d4d');

INSERT INTO USERS (USER_ID, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE_ID)
SELECT
    '941d86f8-8c21-47b5-942a-0f5d3de9f31a',
    'sv004@student.school.edu.vn',
    '$2b$10$dpWgPcUSPz52lisQnwyqW.1JHSX8hEq4UqTmD0ex/XoGK1ZdpagsG',
    'Đỗ Thanh Tuyền',
    R.ROLE_ID
FROM ROLES R WHERE R.ROLE_NAME = 'Student'
AND NOT EXISTS (SELECT 1 FROM USERS WHERE EMAIL = 'sv004@student.school.edu.vn');

INSERT INTO STUDENT_PROFILES (USER_ID, MAJOR, AVERAGE_SCORE, COMPLETED_QUIZ_ATTEMPTS)
SELECT '941d86f8-8c21-47b5-942a-0f5d3de9f31a', 'Kỹ thuật phần mềm', 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM STUDENT_PROFILES WHERE USER_ID = '941d86f8-8c21-47b5-942a-0f5d3de9f31a');


COMMIT;